spring.application.name=Live-Learning_Platform
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3302/live_learning_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowLoadLocalInfile=true
spring.datasource.username=root
spring.datasource.password=06@La1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

